// AUTO-GENERATED by scripts/build-migrated-image-manifest.mjs - do not edit by hand.
// Maps each migrated page slug to its usable full-size PHOTOS (webp/jpg/avif only, no icon PNGs).

export const migratedImages: Record<string, string[]> = {
  "a-complete-guide-to-dgca-ground-classes-in-india-subjects-duration-and-benefits": [
    "/migrated/a-complete-guide-to-dgca-ground-classes-in-india-subjects-duration-and-benefits/BAA-Training-students-Theory-class.webp"
  ],
  "about": [
    "/migrated/about/gallery-5.webp",
    "/migrated/about/gallery-7.webp",
    "/migrated/about/gallery-8.webp",
    "/migrated/about/gallery-9.webp",
    "/migrated/about/nov-5-2021-shell-pastaza-ecuador-light-aircraft-small-runway-amazon-region-ecuador.webp",
    "/migrated/about/private-singleengined-pistonpowered-aircraft-taxiing-airfield-1.webp",
    "/migrated/about/5U2A3973-copy-1.webp",
    "/migrated/about/new-map-copy-1.webp"
  ],
  "about-us": [
    "/migrated/about-us/gallery-5.webp",
    "/migrated/about-us/gallery-7.webp",
    "/migrated/about-us/gallery-8.webp",
    "/migrated/about-us/gallery-9.webp",
    "/migrated/about-us/nov-5-2021-shell-pastaza-ecuador-light-aircraft-small-runway-amazon-region-ecuador.webp",
    "/migrated/about-us/private-singleengined-pistonpowered-aircraft-taxiing-airfield-1.webp",
    "/migrated/about-us/5U2A3973-copy-1.webp",
    "/migrated/about-us/new-map-copy-1.webp"
  ],
  "airbus-a320-type-rating": [
    "/migrated/airbus-a320-type-rating/airbus-a320-taking-off-from-schiphol-airport-with-control-tower-background-cloudy-day_1275033-5738.avif",
    "/migrated/airbus-a320-type-rating/img-51.webp"
  ],
  "airline-cadet-program-interview-training": [
    "/migrated/airline-cadet-program-interview-training/plane-18.webp"
  ],
  "airline-preparation-program": [
    "/migrated/airline-preparation-program/place-flying-sunset-sky_1112-1132.avif"
  ],
  "airline-transport-pilot-license": [
    "/migrated/airline-transport-pilot-license/gallery-33-1.webp",
    "/migrated/airline-transport-pilot-license/gallery-33.webp",
    "/migrated/airline-transport-pilot-license/galler-35.webp"
  ],
  "best-aviation-academy-in-india-for-pilot-training-a-career-ready-curriculum": [
    "/migrated/best-aviation-academy-in-india-for-pilot-training-a-career-ready-curriculum/maxresdefault-22.webp"
  ],
  "best-online-aviation-courses-in-india-flexible-learning-for-future-flyers": [
    "/migrated/best-online-aviation-courses-in-india-flexible-learning-for-future-flyers/skynews-pilot-uk-no-deal-brexit_4417331.webp"
  ],
  "blog": [
    "/migrated/blog/cheerful-young-man-airline-worker-touching-captain-hat-smiling-while-standing-airfield-with-airplane-background-scaled.webp",
    "/migrated/blog/skynews-pilot-uk-no-deal-brexit_4417331.webp",
    "/migrated/blog/BAA-Training-students-Theory-class.webp",
    "/migrated/blog/maxresdefault-22.webp",
    "/migrated/blog/Multi-Engine-Rating.jpg",
    "/migrated/blog/obuka_helikopteri_gama_2_1648052846.webp"
  ],
  "boeing-737-type-rating": [
    "/migrated/boeing-737-type-rating/captain-woman-copilot-getting-ready-fly-airplane-takeoff-with-dashboard-navigation-cockpit-command-airline-crew-fixing-altitude-level-with-control-panel-buttons-flying-plane.webp",
    "/migrated/boeing-737-type-rating/boeing737.webp"
  ],
  "cabin-crew-program": [
    "/migrated/cabin-crew-program/cabin-crew-lift-luggage-bag-airplane.webp",
    "/migrated/cabin-crew-program/young-male-pilots-two-beautiful-flight-attendants-walking-with-linked-arms-r0dh40s868gxpk1efw9q8bbn9amg8fpa0hihc9vh7c.webp",
    "/migrated/cabin-crew-program/IMG_3014.webp"
  ],
  "cadet-pilot-program": [
    "/migrated/cadet-pilot-program/cheerful-young-man-airline-worker-touching-captain-hat-smiling-while-standing-airfield-with-airplane-background-scaled-qox0fbkgypxgxsr1z56rk5km8natj3q3pu32wzidmw.webp",
    "/migrated/cadet-pilot-program/Pilot-qov97uvqe0zp8vzm328yzuyojwrqt1aj7c4mdnd2fc.webp",
    "/migrated/cadet-pilot-program/DSC02177.webp",
    "/migrated/cadet-pilot-program/header-qofy8xavdygpf9c35sxjvmwmmimny6zftj90sytcw8.webp",
    "/migrated/cadet-pilot-program/img-51-qofx88nmnq8ub4medg2q2e6005fyjgckfyntj77hqg.webp"
  ],
  "certified-flight-instructor": [
    "/migrated/certified-flight-instructor/gallery-25.webp",
    "/migrated/certified-flight-instructor/gallery-27.webp",
    "/migrated/certified-flight-instructor/pilot-4-1.webp",
    "/migrated/certified-flight-instructor/train-driver-occupation.webp"
  ],
  "commercial-pilot-license": [
    "/migrated/commercial-pilot-license/plane-14-1.webp",
    "/migrated/commercial-pilot-license/plane-15-1.webp",
    "/migrated/commercial-pilot-license/plane-16-2.webp",
    "/migrated/commercial-pilot-license/plane-7-1.webp"
  ],
  "dgca-ground-classes": [
    "/migrated/dgca-ground-classes/dgca.webp"
  ],
  "diploma-in-aviation": [
    "/migrated/diploma-in-aviation/gallery-20.webp",
    "/migrated/diploma-in-aviation/gallery-21.webp",
    "/migrated/diploma-in-aviation/gallery-22.webp",
    "/migrated/diploma-in-aviation/main-24.webp"
  ],
  "foreign-cpl": [
    "/migrated/foreign-cpl/place-flying-sunset-sky_1112-1132.avif",
    "/migrated/foreign-cpl/ready-flight-rear-view-confident-male-pilot-showing-his-thumb-up-smiling.webp"
  ],
  "helicopter-training": [
    "/migrated/helicopter-training/aircrew-member-flying-plane-from-cockpit-with-dashboard-command-control-panel-using-steering-wheel-control-panel-windscreen-navigation-woman-using-lever-fly-aircraft.webp",
    "/migrated/helicopter-training/commercial-private-helicopter-pilot.webp",
    "/migrated/helicopter-training/HPL.webp",
    "/migrated/helicopter-training/pilot-20.webp",
    "/migrated/helicopter-training/pilot-21.webp",
    "/migrated/helicopter-training/pilot-22.webp"
  ],
  "how-to-start-your-helicopter-flight-training-a-step-by-step-guide": [
    "/migrated/how-to-start-your-helicopter-flight-training-a-step-by-step-guide/obuka_helikopteri_gama_2_1648052846.webp"
  ],
  "ielts-training-program": [
    "/migrated/ielts-training-program/pilot-22.webp",
    "/migrated/ielts-training-program/plane-18.webp"
  ],
  "instrument-rating": [
    "/migrated/instrument-rating/pilot-3.webp",
    "/migrated/instrument-rating/pilot-4.webp",
    "/migrated/instrument-rating/pilot-5.webp",
    "/migrated/instrument-rating/plane-7-2.webp"
  ],
  "license-conversion-course": [
    "/migrated/license-conversion-course/images-33.webp",
    "/migrated/license-conversion-course/IMG_3014-qp5yf10z8riryf8p9ahofq6bel160vklll2l8tef2w.webp",
    "/migrated/license-conversion-course/IMG_3015-qp5yf7ls4w6cj3be0yx9nwzt3r99xcw3leyt9zn8rk.webp",
    "/migrated/license-conversion-course/IMG_3056-qp5yeug1h7oc0jui5t8hp0bcsd24xlfuvlu0k46r6o.webp"
  ],
  "multi-engine-instrument-rating-meir": [
    "/migrated/multi-engine-instrument-rating-meir/Multi-Engine-Rating.jpg"
  ],
  "multi-engine-rating": [
    "/migrated/multi-engine-rating/gallery-39.webp",
    "/migrated/multi-engine-rating/gallery-40-1.webp",
    "/migrated/multi-engine-rating/gallery-40.webp",
    "/migrated/multi-engine-rating/pilot-3-1.webp"
  ],
  "night-rating-progam": [
    "/migrated/night-rating-progam/gallery-28.webp",
    "/migrated/night-rating-progam/gallery-29.webp",
    "/migrated/night-rating-progam/gallery-30.webp",
    "/migrated/night-rating-progam/gallery-31.webp"
  ],
  "pilot-training-in-australia": [
    "/migrated/pilot-training-in-australia/plane-13.webp",
    "/migrated/pilot-training-in-australia/plane-14.webp",
    "/migrated/pilot-training-in-australia/plane-15.webp",
    "/migrated/pilot-training-in-australia/australia.webp"
  ],
  "pilot-training-in-canada": [
    "/migrated/pilot-training-in-canada/plane-6.webp",
    "/migrated/pilot-training-in-canada/plane-7.webp",
    "/migrated/pilot-training-in-canada/plane-8.webp"
  ],
  "pilot-training-in-india": [
    "/migrated/pilot-training-in-india/plane-10.webp",
    "/migrated/pilot-training-in-india/plane-11.webp",
    "/migrated/pilot-training-in-india/plane-12.webp",
    "/migrated/pilot-training-in-india/india.webp"
  ],
  "pilot-training-in-new-zealand": [
    "/migrated/pilot-training-in-new-zealand/pilot-3.webp",
    "/migrated/pilot-training-in-new-zealand/pilot-4.webp",
    "/migrated/pilot-training-in-new-zealand/pilot-5.webp",
    "/migrated/pilot-training-in-new-zealand/NEWZEALAND.webp"
  ],
  "pilot-training-in-south-africa": [
    "/migrated/pilot-training-in-south-africa/plane-16.webp",
    "/migrated/pilot-training-in-south-africa/plane-17.webp",
    "/migrated/pilot-training-in-south-africa/plane-18.webp",
    "/migrated/pilot-training-in-south-africa/south-africa.webp"
  ],
  "pilot-training-in-usa": [
    "/migrated/pilot-training-in-usa/cheerful-woman-flight-attendant-standing-outdoors-airport.webp",
    "/migrated/pilot-training-in-usa/private-singleengined-pistonpowered-aircraft-taxiing-airfield.webp",
    "/migrated/pilot-training-in-usa/young-handsome-businessman-standing-near-private-plane.webp"
  ],
  "pre-cadet-program": [
    "/migrated/pre-cadet-program/aircrew-member-flying-plane-from-cockpit-with-dashboard-command-control-panel-using-steering-wheel-control-panel-windscreen-navigation-woman-using-lever-fly-aircraft.webp"
  ],
  "private-pilot-license": [
    "/migrated/private-pilot-license/pilot-3.webp",
    "/migrated/private-pilot-license/pilot-4.webp",
    "/migrated/private-pilot-license/pilot-5.webp",
    "/migrated/private-pilot-license/plane-16-1.webp"
  ],
  "windchasers-meet-the-team": [
    "/migrated/windchasers-meet-the-team/one-confident-man-standing-uniform-looking-camera-generated-by-ai-scaled-qq9ovvmrxkfmnqpc2qk66a2ei5aus3vzvpu0kla4w4.webp",
    "/migrated/windchasers-meet-the-team/Hemanth-qyhi1cz9fgcq1x53kazwkbqtf5x7l65oah76tnj22s.webp",
    "/migrated/windchasers-meet-the-team/IMG_6972-qyhhlawiocddpqgsbv4cgvmc372h3ber2zzkohc6dg.webp",
    "/migrated/windchasers-meet-the-team/IMG_6973-qyhhju9k1mdbnkl8v8d8l8witm9x49ls7rgdszi81w.webp",
    "/migrated/windchasers-meet-the-team/Shreyas-qyhhzmxwwdzsrnn7mk6izree7qezh5be1y555e31hg.webp",
    "/migrated/windchasers-meet-the-team/Vijay-qyhi4fw7twkk3wnzkmxvqjr7imqitge01q6hgaylok.webp"
  ]
};
